#!/bin/bash

# Auto-Build Environment Setup
# Generated by Planner Agent for NAITIVE RFP Radar
# Spec: 001-deploy

set -e

echo "========================================"
echo "RFP Radar Development Environment Setup"
echo "========================================"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

PROJECT_ROOT="/Users/chris/ai/Multi-Agent-Custom-Automation-Engine-Solution-Accelerator"

# Navigate to project root
cd "$PROJECT_ROOT"

echo ""
echo -e "${YELLOW}Step 1: Creating RFP Radar directory structure${NC}"
echo "========================================"

# Create directory structure
mkdir -p src/rfp_radar/scrapers
mkdir -p src/rfp_radar/tests

echo -e "${GREEN}✓ Directory structure created${NC}"

echo ""
echo -e "${YELLOW}Step 2: Setting up Python virtual environment${NC}"
echo "========================================"

# Create virtual environment for RFP Radar if it doesn't exist
if [ ! -d ".venv-rfp" ]; then
    python3 -m venv .venv-rfp
    echo -e "${GREEN}✓ Virtual environment created${NC}"
else
    echo -e "${GREEN}✓ Virtual environment already exists${NC}"
fi

# Activate virtual environment
source .venv-rfp/bin/activate

echo ""
echo -e "${YELLOW}Step 3: Installing dependencies${NC}"
echo "========================================"

# Install base dependencies for development
pip install --quiet pydantic python-dotenv requests azure-storage-blob azure-search-documents slack-sdk pytest flake8

echo -e "${GREEN}✓ Base dependencies installed${NC}"

echo ""
echo -e "${YELLOW}Step 4: Verifying Azure CLI (optional)${NC}"
echo "========================================"

if command -v az &> /dev/null; then
    echo -e "${GREEN}✓ Azure CLI available${NC}"
    az --version | head -1
else
    echo -e "${YELLOW}⚠ Azure CLI not found - Bicep validation will be skipped${NC}"
fi

echo ""
echo -e "${YELLOW}Step 5: Verifying Docker (optional)${NC}"
echo "========================================"

if command -v docker &> /dev/null; then
    echo -e "${GREEN}✓ Docker available${NC}"
    docker --version
else
    echo -e "${YELLOW}⚠ Docker not found - container builds will be skipped${NC}"
fi

echo ""
echo "========================================"
echo -e "${GREEN}Environment Ready!${NC}"
echo "========================================"
echo ""
echo "Project Root: $PROJECT_ROOT"
echo "RFP Radar Path: src/rfp_radar/"
echo "Virtual Environment: .venv-rfp"
echo ""
echo "To activate the environment manually:"
echo "  source .venv-rfp/bin/activate"
echo ""
echo "To run RFP Radar locally (after implementation):"
echo "  python src/rfp_radar/main.py"
echo ""
echo "To run tests:"
echo "  python -m pytest src/rfp_radar/tests/ -v"
echo ""
echo "To build Docker container:"
echo "  docker build -t rfp-radar:latest -f src/rfp_radar/Dockerfile src/rfp_radar/"
echo ""
