"""Lead Generation Utility Functions.

This module provides utility functions for lead generation operations
including revenue estimation, dossier generation, and email templates.
"""

from typing import TYPE_CHECKING

# Direct imports for utilities (no external dependencies)
from .revenue_heuristics import (
    estimate_revenue,
    get_industry_multiplier,
    calculate_review_score,
    is_qualified_revenue,
    INDUSTRY_MULTIPLIERS,
    MIN_QUALIFIED_REVENUE,
    MAX_QUALIFIED_REVENUE,
)

from .dossier_template import (
    generate_dossier,
    generate_dossier_from_dict,
    validate_dossier_sections,
    is_dossier_valid,
    get_default_pain_points,
    generate_gotcha_qas_from_data,
    DossierData,
    DossierStatus,
    CompanyOverview,
    Service,
    TeamMember,
    PainPoint,
    GotchaQA,
    Competitor,
)

from .voice_personality import (
    generate_personality,
    generate_personality_prompt,
    generate_personality_from_dossier,
    get_available_tones,
    get_available_speeds,
    get_supported_industries,
    VoicePersonalityConfig,
    VoicePersonalityTone,
    VoiceSpeed,
    BusinessContext,
    PersonalityTemplate,
    INDUSTRY_CONVERSATION_HINTS,
)

from .branding_injector import (
    inject_branding,
    inject_branding_from_lead,
    branding_config_from_lead,
    validate_branding_config,
    get_industry_colors,
    get_industry_tagline,
    format_env_file,
    format_vercel_env_json,
    merge_branding_configs,
    BrandingConfig,
    BrandingValidationResult,
    INDUSTRY_COLORS,
    INDUSTRY_TAGLINES,
    DEFAULT_BRANDING,
)

from .email_templates import (
    generate_cold_email,
    generate_cold_email_from_dict,
    generate_subject,
    get_available_styles,
    get_available_variants,
    get_industry_subjects,
    validate_template,
    is_template_valid,
    EmailTemplate,
    GeneratedEmail,
    EmailStyle,
    EmailVariant,
    CANSpamFooter,
    PersonalizationToken,
    INDUSTRY_SUBJECTS,
    INDUSTRY_PAIN_HOOKS,
    HUMOROUS_OPENERS,
)

from .daily_report import (
    generate_daily_report,
    generate_daily_report_from_stats,
    calculate_domain_health_score,
    generate_alerts,
    generate_recommendations,
    aggregate_metrics,
    get_health_status_description,
    DailyReport,
    EmailMetricsSnapshot,
    BounceAnalysis,
    CampaignSummary,
    DomainHealthStatus,
    ReportPeriod,
    HEALTH_WEIGHTS,
    BENCHMARKS,
)

__all__ = [
    # Revenue heuristics
    "estimate_revenue",
    "get_industry_multiplier",
    "calculate_review_score",
    "is_qualified_revenue",
    "INDUSTRY_MULTIPLIERS",
    "MIN_QUALIFIED_REVENUE",
    "MAX_QUALIFIED_REVENUE",
    # Dossier template
    "generate_dossier",
    "generate_dossier_from_dict",
    "validate_dossier_sections",
    "is_dossier_valid",
    "get_default_pain_points",
    "generate_gotcha_qas_from_data",
    "DossierData",
    "DossierStatus",
    "CompanyOverview",
    "Service",
    "TeamMember",
    "PainPoint",
    "GotchaQA",
    "Competitor",
    # Voice personality
    "generate_personality",
    "generate_personality_prompt",
    "generate_personality_from_dossier",
    "get_available_tones",
    "get_available_speeds",
    "get_supported_industries",
    "VoicePersonalityConfig",
    "VoicePersonalityTone",
    "VoiceSpeed",
    "BusinessContext",
    "PersonalityTemplate",
    "INDUSTRY_CONVERSATION_HINTS",
    # Branding injector
    "inject_branding",
    "inject_branding_from_lead",
    "branding_config_from_lead",
    "validate_branding_config",
    "get_industry_colors",
    "get_industry_tagline",
    "format_env_file",
    "format_vercel_env_json",
    "merge_branding_configs",
    "BrandingConfig",
    "BrandingValidationResult",
    "INDUSTRY_COLORS",
    "INDUSTRY_TAGLINES",
    "DEFAULT_BRANDING",
    # Email templates
    "generate_cold_email",
    "generate_cold_email_from_dict",
    "generate_subject",
    "get_available_styles",
    "get_available_variants",
    "get_industry_subjects",
    "validate_template",
    "is_template_valid",
    "EmailTemplate",
    "GeneratedEmail",
    "EmailStyle",
    "EmailVariant",
    "CANSpamFooter",
    "PersonalizationToken",
    "INDUSTRY_SUBJECTS",
    "INDUSTRY_PAIN_HOOKS",
    "HUMOROUS_OPENERS",
    # Daily report
    "generate_daily_report",
    "generate_daily_report_from_stats",
    "calculate_domain_health_score",
    "generate_alerts",
    "generate_recommendations",
    "aggregate_metrics",
    "get_health_status_description",
    "DailyReport",
    "EmailMetricsSnapshot",
    "BounceAnalysis",
    "CampaignSummary",
    "DomainHealthStatus",
    "ReportPeriod",
    "HEALTH_WEIGHTS",
    "BENCHMARKS",
]
